name: "Frogbot Scans"
description: "Performs Frogbot scans on repositories or pull requests
author: "JFrog"
inputs:
    oidc-provider-name:
        description: "Provider Name's value that was set in OpenId Connect integration in the JFrog platform."
        required: false
    oidc-audience:
        description: "By default, this is the URL of the GitHub repository owner, such as the organization that owns the repository."
        required: false
runs:
    using: "node20"
    main: "lib/main.js"
branding:
    icon: "terminal"
    color: "green"
